/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthenticationRequest {

  /**
   * Email is required and should be valid
   */
  email: string;

  /**
   * Password is required and should be at least 8 characters
   */
  password: string;
}
