/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {

  /**
   * Author name is required and should be at least 1 character
   */
  author_name: string;
  id?: number;

  /**
   * ISBN is required and should be at least 10 characters
   */
  isbn: string;

  /**
   * Shareable must be set
   */
  shareable: boolean;

  /**
   * Synopsis is required and should be at least 10 characters
   */
  synopsis: string;

  /**
   * Title is required and should be at least 1 character
   */
  title: string;
}
