/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackRequest {

  /**
   * Book ID is required
   */
  book_id: number;

  /**
   * Comment is required and should be at least 1 character
   */
  comment: string;

  /**
   * Note must be between 0 and 5
   */
  note: number;
}
