/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PageResponse {
  content: Array<{
}>;
  first: boolean;
  last: boolean;
  number: number;
  size: number;
  total_elements: number;
  total_pages: number;
}

