/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {

  /**
   * Email is required and should be valid: ex -> greatness@tali.de
   */
  email: string;

  /**
   * First name is required and should be at least 1 character
   */
  first_name: string;

  /**
   * Last name is required and should be at least 1 character
   */
  last_name: string;

  /**
   * Password is required and should be at least 8 characters
   */
  password: string;
}
