/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findAllFeedbackByBook } from '../fn/feedback/find-all-feedback-by-book';
import { FindAllFeedbackByBook$Params } from '../fn/feedback/find-all-feedback-by-book';
import { PageResponse } from '../models/page-response';
import { saveFeedback } from '../fn/feedback/save-feedback';
import { SaveFeedback$Params } from '../fn/feedback/save-feedback';


/**
 * Handles everything related to Feedback component
 */
@Injectable({ providedIn: 'root' })
export class FeedbackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveFeedback()` */
  static readonly SaveFeedbackPath = '/feedbacks/';

  /**
   * saveFeedback.
   *
   * Submit data to save a new Feedback
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveFeedback()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback$Response(params: SaveFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveFeedback(this.http, this.rootUrl, params, context);
  }

  /**
   * saveFeedback.
   *
   * Submit data to save a new Feedback
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveFeedback$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback(params: SaveFeedback$Params, context?: HttpContext): Observable<number> {
    return this.saveFeedback$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findAllFeedbackByBook()` */
  static readonly FindAllFeedbackByBookPath = '/feedbacks/book/{book-id}';

  /**
   * findAllFeedbackByBook.
   *
   * Get all feedbacks for given Book
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllFeedbackByBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllFeedbackByBook$Response(params: FindAllFeedbackByBook$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponse>> {
    return findAllFeedbackByBook(this.http, this.rootUrl, params, context);
  }

  /**
   * findAllFeedbackByBook.
   *
   * Get all feedbacks for given Book
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllFeedbackByBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllFeedbackByBook(params: FindAllFeedbackByBook$Params, context?: HttpContext): Observable<PageResponse> {
    return this.findAllFeedbackByBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponse>): PageResponse => r.body)
    );
  }

}
